src/apps/access/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'access'
urlpatterns = [
    path('', views.loginView, name='login'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('register/', views.registerView, name='register'),
]

src/apps/beacons/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'beacons'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('details/id=<int:id>', views.details, name='details'),
    path('update', views.update, name='update'),
    path('<slug:beacon_type>', views.per_type, name='type'),
]

src/beacon/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # temprorary
    url(r'',                include(('apps.beacons.urls', 'beacons'),           namespace="index")),
    url(r'^beacons/',       include(('apps.beacons.urls', 'beacons'),           namespace="beacons")),
    url(r'^access/',        include(('apps.access.urls', 'access'),             namespace="access")),
    url(r'^profile_page/',  include(('apps.profile_page.urls', 'profile_page'), namespace="profile_page")),
    url(r'^polls/',         include(('polls.urls', 'polls'),                    namespace="polls")),
    url(r'^admin/',         admin.site.urls),
]

src/lost/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # temprorary
    url(r'',            include(('apps.mainpage.urls', 'mainpage'),     namespace="mainpage")),
    url(r'^locations/', include(('apps.locations.urls', 'locations'),   namespace="locations")),
    url(r'^polls/',     include(('polls.urls', 'polls'),                namespace="polls")),
    url(r'^admin/',     admin.site.urls),
    #path('polls/', include('polls.urls')),
    #path('admin/', admin.site.urls),
]

src/polls/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

src/templates/base/beacons_loop.html
{% for type_short, type in beacon_types %}

    {% if beacons %}
        <button class="btn btn-primary btn-block" data-toggle="collapse" data-target="#collapse{{type_short}}">{{type}}</button>
        <div id="collapse{{type_short}}" class="collapse in">

            <div class="panel-group" id="accordion">
                {% for beacon in beacons %}
                    {% if beacon.beacon_type == type_short %}

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a href="#extra_info{{beacon.id}}" id="beacon{{beacon.id}}"  class="btn btn-primary btn-block" data-toggle="collapse" data-parent="#accordion">{{beacon.name}} </a>
                        </div>
                        <div id="extra_info{{beacon.id}}" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Search icon on a styled button:
                                    <a href="{% url 'beacons:details' id=beacon.id %}" class="btn btn-info"><span class="glyphicon glyphicon-arrow-right"></span> Visit</a>
                                </p>
                            </div>
                        </div>
                    </div>

                    {% endif %}
                {% endfor %}
            </div>

        </div>
    {% else %}
        <a href="{% url 'beacons:type' type_short %}"  class="btn btn-primary btn-block" role="button">{{type}}</a>
    {% endif %}

{% endfor %}

src/templates/base/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} {{title}} {% endblock %} </title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    {% block scripts_head %}{% endblock %}

</head>

<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-default">
        {% block navbar %}
        <div class="container-fluid">

            <!-- LEFT -->
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'beacons:index' %}">Beacon</a>
            </div>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'beacons:add' %}">Add</a></li>
            </ul>

            <!-- RIGHT -->
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'profile_page:index' %}">Your Profile</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'access:logout' %}">Log out</a></li>
                    </ul>
                    </li>
                {% else %}
                        <li><a href="{% url 'access:login' %}">Log in</a></li>
                {% endif %}

            </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->


        {% endblock %}
    </nav>


    {% block main %}
    <!-- MAINPART -->
    <div class="row"> <!-- mainpart -->
        {{debug_text}}
        <!-- LEFT -->
        <div class="col-xs-2"> <!-- left -->
            <div class="container-fluid">
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                    </div>
                </form>
            </div>
        </div> <!-- left -->

        <!-- RIGHT -->
        <div class="col-xs-10"> <!-- right -->
            <div class="container-fluid">

                <div class="row">
                    <div class="col-sm-12">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-sm-12">
                        {% block content_left %}
                        {% endblock %}
                    </div>

                    <div class="col-md-8 col-sm-12">
                        {% block content_right %}
                        {% endblock %}
                    </div>
                </div>
            </div><!-- /.container -->
        </div> <!-- right -->
    </div> <!-- mainpart -->
    {% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    {% block scripts_body %}{% endblock %}
    {% block scripts_body_gmap %}{% endblock %}

</body>
</html>