src/apps/beacons/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'beacons'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('details/id=<int:id>', views.details, name='details'),
    path('update', views.update, name='update'),
    path('<slug:beacon_type>', views.per_type, name='type'),
]

src/beacon/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # temprorary
    url(r'',                include(('apps.beacons.urls', 'beacons'),           namespace="index")),
    url(r'^beacons/',       include(('apps.beacons.urls', 'beacons'),           namespace="beacons")),
    url(r'^access/',        include(('apps.access.urls', 'access'),             namespace="access")),
    url(r'^profile_page/',  include(('apps.profile_page.urls', 'profile_page'), namespace="profile_page")),
    url(r'^polls/',         include(('polls.urls', 'polls'),                    namespace="polls")),
    url(r'^admin/',         admin.site.urls),
]

src/lost/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # temprorary
    url(r'',            include(('apps.mainpage.urls', 'mainpage'),     namespace="mainpage")),
    url(r'^locations/', include(('apps.locations.urls', 'locations'),   namespace="locations")),
    url(r'^polls/',     include(('polls.urls', 'polls'),                namespace="polls")),
    url(r'^admin/',     admin.site.urls),
    #path('polls/', include('polls.urls')),
    #path('admin/', admin.site.urls),
]

src/apps/beacons/models.py
from django.db import models
from django.contrib.auth.models import User

class Beacon(models.Model):
    beacon_choices = [
    ('LF', 'Lost and Found'),
    ('SL', 'Stolen item'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=-1)
    latitude = models.DecimalField(default=0, max_digits=18, decimal_places=15)
    longitude = models.DecimalField(default=0, max_digits=18, decimal_places=15)
    name = models.CharField(max_length=200)
    beacon_type = models.CharField(
        max_length=2, 
        choices=beacon_choices,
        default='LF',
    )
    description = models.CharField(max_length=1000)


    def __str__(self):
        return self.name

src/apps/beacons/forms.py
from django.db import models
from django import forms
from .models import Beacon

class BeaconFullForm(forms.ModelForm):
    class Meta:
        model = Beacon
        fields = ['name', 'latitude', 'longitude', 'beacon_type', 'description']
        widgets = {
            'description': forms.Textarea(),
        }
        
class BeaconAddForm(forms.ModelForm):
    class Meta:
        model = Beacon
        fields =['name', 'latitude', 'longitude', 'beacon_type', 'description']

        widgets = {
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
            'description': forms.Textarea(attrs={'cols': 40, 'rows': 5}),
        }

src/apps/beacons/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django import forms
from common.utilities import index_context
from .models import Beacon
from .forms import BeaconFullForm, BeaconAddForm


def render_add_form(request, debug_text = "", is_add = 1,):
    # Provide empty form
    if is_add:
        form = BeaconAddForm()
    else:
        form = BeaconFullForm()

    context = {
        'form' : form,
    }
    if debug_text:
        context.update({'debug_text': "Please fix the form errors"})

    return HttpResponse(render(request, 'beacons/add.html', context))
# Utilities - end }

@login_required
def index(request):
    return HttpResponse(render(request, 'beacons/index.html', index_context))

@login_required
def per_type(request, beacon_type=None):
    context = {
        'beacons': Beacon.objects.filter(beacon_type=beacon_type),
        'beacon_types': [b_type for b_type in Beacon.beacon_choices if b_type[0] == beacon_type],
    }
    return HttpResponse(render(request, 'beacons/per_type.html', context))

@login_required
# Used for both add/show/update
def add(request, id=None):
    if request.method == 'POST':
        # Validate and add
        form = BeaconFullForm(request.POST)
        if form.is_valid():
            beacon = Beacon.objects.create(
                user_id =       request.user.id, 
                name =          form.cleaned_data.get('name'), 
                latitude =      form.cleaned_data.get('latitude'), 
                longitude =     form.cleaned_data.get('longitude'),
                beacon_type =   form.cleaned_data.get('beacon_type'),
                description =   form.cleaned_data.get('description')
            )
            # Update the database
            beacon.save()

            context = {
                'debug_text': " We saved beacon with name " + beacon.name,
            }
            context.update(index_context)
            return HttpResponse(render(request, 'beacons/index.html', context))
        else:
            return render_add_form(request, "Please fix the form errors")
    else:
        return render_add_form(request)

@login_required
def details(request, id=None):
    # If we display a beacon
    try:
        beacon = Beacon.objects.get(id=id)
    except:
        raise Http404("Beacon with id" + int(id) + "exist")

    context = {
        'beacon_id': id,
        'form' : BeaconFullForm(instance=beacon),
        'beacon' : beacon,
    }
    return HttpResponse(render(request, 'beacons/details.html', context))

@login_required
def update(request):

    if request.method == 'POST':
        beacon = Beacon.objects.get(pk=request.POST['beacon_id'])

        if '_delete' in request.POST:
            beacon.delete()
            context = {
                'debug_text': " We deleted beacon with name " + beacon.name ,
            }
            context.update(index_context)
            return HttpResponse(render(request, 'beacons/index.html', index_context))
        else:
            # Assume we are in submit case
            form = BeaconFullForm(request.POST)
            if form.is_valid():

                beacon.user_id = request.user.id
                beacon.name = form.cleaned_data.get('name')
                beacon.latitude = form.cleaned_data.get('latitude')
                beacon.longitude = form.cleaned_data.get('longitude')
                beacon.beacon_type = form.cleaned_data.get('beacon_type')
                beacon.description = form.cleaned_data.get('description')

                beacon.save()

                context = {
                    'debug_text': " We updated beacon with name " + beacon.name ,
                }
                context.update(index_context)
                return HttpResponse(render(request, 'beacons/index.html', index_context))

            else:
                # Here we should handle if the form input are invalid
                context = {
                    'debug_text': "Please fix the form errors",
                    'form' : form,
                }
                return HttpResponse(render(request, 'beacons/index.html', context))
    else:
        raise Http404("Page does not exist")
   

src/apps/beacons/templates/beacons/add.html
{% extends "beacons/base.html" %}

{% block title %} Lid a Beacon {% endblock %}

{% load static %}

{% block scripts_head %} 
<script src="{% static "js/gmap.js" %}"></script>   
{% endblock %}

{% block content_left %}
  <div class="container-fluid">

    <form action="{% url 'beacons:add' %}" method="POST" class="form-horizontal">
      {% csrf_token %}
      <!-- Form Fields { -->
      {% for field in form %}
            {% if field.is_hidden != 1 %}
              <div class="form-group">
              {{ field.errors }}
              {{ field.label_tag }} 
            {% endif %}

            {{ field }}

            {% if field.is_hidden != 1 %}
              {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
              {% endif %}

              </div>
            {% endif %}

      {% endfor %}
      <!-- Form Fields } -->
      <!-- GEOCODE input { -->
      <div class="form-group">
        <div class="input-group">
          <input id="address" class="form-control" type="textbox" value="Plovdiv, Bulgaria" />

          <div class="input-group-btn">
            <button id="geocode" class="btn btn-default"  type="button" value="Search Place">
              <i class="glyphicon glyphicon-search"></i>
            </button>
          </div>
        </div>
      </div>
      <!-- GEOCODE input } -->

      <!-- Save Beacon-->
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

    </form>

    {% if form.subject.errors %}
        <ol>
        {% for error in form.subject.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
        </ol>
    {% endif %}

  </div>

{% endblock %}

{% block content_right %}
  <div class="container-fluid">
    <div id="map" style="height:400px;"></div>
  </div>

{% endblock %}

{% block scripts_body %}

  <script defer>
    function initMap() {
        /*
        * This creates a map with start point Plovdiv
        */
        var beacon_markers = {
          LatLong : new google.maps.LatLng(42.148104117060754, 24.755662688914725), 
          id : -1  
        }
        initMapTemplate( beacon_markers );
    }
  </script>

{% endblock %}

src/apps/beacons/templates/beacons/base.html
{% extends "base/index.html" %}

{% block scripts_body_gmap %}

<!-- Async script executes immediately and must be after any DOM elements used in callback. -->
<script
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCvbgILGvzWiIFiv1P2aS8ygpO2VTvIqhs&callback=initMap&libraries=&v=weekly"
  async
></script>

{% endblock %}

src/apps/beacons/templates/beacons/details.html
{% extends "beacons/base.html" %}

{% block title %} Details {% endblock %}

{% load static %}

{% block scripts_head %} 
<script src="{% static "js/gmap.js" %}"></script>   
{% endblock %}

{% block content_left %}

  <div class="container-fluid">
    <form action="{% url 'beacons:update' %}" method="POST" class="form-horizontal">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
              {{ field.errors }}
              {{ field.label_tag }} {{ field }}
              {% if field.help_text %}
              <p class="help">{{ field.help_text|safe }}</p>
              {% endif %}
            </div>
        {% endfor %}
        <input type="hidden" id="beacon_id" name="beacon_id" value={{beacon_id}}>

        <div class="form-group">
          <button type="submit" class="btn btn-primary" name="_submit" value="submit">Submit</button>
          <button type="submit" class="btn btn-danger" name="_delete" value="delte">Delete</button>
        </div>

    </form>

    {% if form.subject.errors %}
        <ol>
        {% for error in form.subject.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
        </ol>
    {% endif %}
  </div>
{% endblock %}


{% block content_right %}

  <div class="container-fluid">
    <div id="map" style="height:400px;"></div>
  </div>

{% endblock %}

{% block scripts_body %}

  <script defer>

    function initMap() {
      var beacon_markers = {
        LatLong : new google.maps.LatLng( {{beacon.latitude}}, {{beacon.longitude}}), 
        id : "beacon"+{{beacon.id}} 
      }
      initMapTemplate(beacon_markers);
    }

  </script>

{% endblock %}

src/apps/beacons/templates/beacons/index.html
{% extends "base/index.html" %}

{% block title %} Beacons {% endblock %}

{% load static %}

{% block content %}

  <div class="container-fluid">
      {% include "base/beacons_loop.html" %}
  </div>

{% endblock %}

src/apps/beacons/templates/beacons/per_type.html
{% extends "beacons/base.html" %}

{% block title %} Beacons {% endblock %}

{% load static %}

{% block scripts_head %} 
<script src="{% static "js/gmap.js" %}"></script>   
{% endblock %}

{% block content_left %}
    <div class="container-fluid">
        {% include "base/beacons_loop.html" %}
    </div>
{% endblock %}

{% block content_right %}

    <div class="container-fluid">
        <div id="map" style="height:400px;"></div>
    </div>
{% endblock %}

{% block scripts_body %}

    <script defer>
        function initMap() {
            /*
            * First marker coordinates
            */
            var beacon_markers = []

            {% for beacon in beacons %}
                beacon_markers.push({
                    LatLong : new google.maps.LatLng( {{ beacon.latitude|safe }},  {{ beacon.longitude|safe }}),
                    id : "beacon" + {{ beacon.id|safe }} 
                })
            {% endfor %}
            map = initMapTemplate(beacon_markers,  "map", false, false, false , 5);

        }
    </script>

{% endblock %}