src/apps/access/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'access'
urlpatterns = [
    path('', views.loginView, name='login'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('register/', views.registerView, name='register'),
]

src/beacon/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # temprorary
    url(r'',                include(('apps.beacons.urls', 'beacons'),           namespace="index")),
    url(r'^beacons/',       include(('apps.beacons.urls', 'beacons'),           namespace="beacons")),
    url(r'^access/',        include(('apps.access.urls', 'access'),             namespace="access")),
    url(r'^profile_page/',  include(('apps.profile_page.urls', 'profile_page'), namespace="profile_page")),
    url(r'^polls/',         include(('polls.urls', 'polls'),                    namespace="polls")),
    url(r'^admin/',         admin.site.urls),
]

src/lost/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # temprorary
    url(r'',            include(('apps.mainpage.urls', 'mainpage'),     namespace="mainpage")),
    url(r'^locations/', include(('apps.locations.urls', 'locations'),   namespace="locations")),
    url(r'^polls/',     include(('polls.urls', 'polls'),                namespace="polls")),
    url(r'^admin/',     admin.site.urls),
    #path('polls/', include('polls.urls')),
    #path('admin/', admin.site.urls),
]

src/apps/access/models.py
from django.db import models

src/apps/access/forms.py
from django.db import models
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control '}))

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

src/apps/access/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from common.utilities import index_context
from .forms import LoginForm, RegisterForm

def loginView(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                context = {
                    'text': "loged_in " + username,
                }
                context.update(index_context)
                return HttpResponse(render(request, 'beacons/index.html', context))

            else:
                context = {
                    'form' : form,
                    'text': 'Login failed',
                }
                return HttpResponse(render(request, 'access/login.html', context))

                
        else:
            context = {
                'form' : form,
            }
            return HttpResponse(render(request, 'access/login.html', context))
    else:
        context = {
            'form' : LoginForm(),
        }
        return HttpResponse(render(request, 'access/login.html', context))

def logoutView(request):
    logout(request)
    context = {
        'text': " You are now loged out! ",
    }

    return HttpResponse(render(request, 'beacons/index.html', context))

def registerView(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():

            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name

            user.save()

            context = {
                'text': "You just registered with first_name " + first_name + " last_name " + last_name + " username " + " email " + email + " password " + str(password),
            }
            context.update(index_context)
            return HttpResponse(render(request, 'beacons/index.html', context))
        else:
            context = {
                'form' : form,
            }
            return HttpResponse(render(request, 'access/register.html', context))
    else:
        context = {
            'form' : RegisterForm(),
        }
        return HttpResponse(render(request, 'access/register.html', context))

    return HttpResponse(render(request, 'access/register.html', context))

src/apps/access/templates/access/login.html
{% extends "access/template.html" %}
{% block grid_size %}"col-md-4 col-md-offset-4"{% endblock %}
{% block title %} Log in {% endblock %}
{% block header %} Log in {% endblock %}
{% block register_link %} 
<a href="{% url 'access:register' %}" class="btn btn-link" role="button">Register</a>
{% endblock %}
{% block action %}"{% url 'access:login' %}"{% endblock %}

src/apps/access/templates/access/register.html
{% extends "access/template.html" %}
{% block grid_size %}"col-md-6 col-md-offset-3"{% endblock %}
{% block title %} Register {% endblock %}
{% block header %} Register {% endblock %}
{% block action %}"{% url 'access:register' %}"{% endblock %}

src/apps/access/templates/access/template.html
{% extends "base/index.html" %}
{% load custom_tags %}

{% block title %} {% endblock %}

{% block main %}
<div class="row">
    <div class={% block grid_size %}{% endblock %}>
        <div class="container">
            <div class="page-header">
                <h1>
                {% block header %}
                {% endblock %}
                </h1>
            </div>
        </div>

        <form action={% block action %}{% endblock %} method="POST" class="form-horizontal">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field|form_label_with_classes:"control-label col-sm-2"}} 
                    <div class="col-sm-10">
                        {{ field|add_class:"form-control" }}
                    </div>
                </div>
            {% endfor %}
            
            <button type="submit" class="btn btn-primary">Submit</button>

            {% block register_link %} 
            {% endblock %}

        </form>

        {% if form.subject.errors %}
            <ol>
            {% for error in form.subject.errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
            </ol>
        {% endif %}

    </div>
</div>
{% endblock %}